# -*- coding: utf-8 -*-
"""AfterMeet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uS8XMPHT2x_fp0DP0ouW-vwWsx6OwazM
"""

pip install cohere python-dotenv python-dateutil

# Cell 3: Setup Cohere API Client and Qdrant Cloud
load_dotenv()

# Cohere API setup
COHERE_API_KEY = os.getenv("COHERE_API_KEY", "tClpQg7NqMYbifQHULAnIdkw2iCdyzGP4riTdPSY")
co = cohere.Client(COHERE_API_KEY)

# Qdrant Cloud setup
QDRANT_URL = "https://c2d56d13-ea15-4874-a400-44f176928962.us-east4-0.gcp.cloud.qdrant.io:6333"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.ofQ0-Jr-6WwpFWQafGeaBb8r_Lk6uFdt4dqHr8IrMMs"

qdrant_client = QdrantClient(
    url=QDRANT_URL,
    api_key=QDRANT_API_KEY,
)

# Initialize Sentence Transformer model
print("Loading Sentence Transformer model...")
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')  # 384 dimensions, fast and efficient
EMBEDDING_DIM = 384

# Collection name for storing meeting transcripts
COLLECTION_NAME = "meeting_transcripts"

print("✓ Cohere client initialized successfully")
print("✓ Qdrant Cloud client initialized successfully")
print("✓ Sentence Transformer model loaded")
print(f"\nExisting collections: {qdrant_client.get_collections()}")

RAW_TRANSCRIPT = """
Dev: Alright, let's get started. Hackathon is in three weeks, so we need a clear plan today.
Farhaan: Agreed. First question is what problem statement we're locking in.
Aaleya: I still think the AI meeting summarizer is strong, especially with task extraction.
Yash: It's strong, but a lot of teams will probably do something similar.
Dev: True, but our edge is urgency detection and action ownership.
Farhaan: Plus end-to-end pipeline, not just a demo.
Aaleya: We need to be careful with scope though. Hackathons punish overengineering.
Yash: Backend-wise, I can handle ingestion and API scaffolding quickly.
Dev: What about frontend?
Aaleya: I can do a clean UI, but I'll need finalized data contracts early.
Farhaan: That means Dev and I should freeze the output schema by this weekend.
Dev: Yes, otherwise integration will be painful.
Yash: What's the biggest risk right now?
Farhaan: Honestly, model latency. If summaries take too long, judges will notice.
Aaleya: Can we fake real-time with partial updates?
Dev: Possibly. Even showing progress would help.
Yash: Another risk is dataset quality. Do we have enough test transcripts?
Dev: Not yet. We should generate synthetic ones.
Farhaan: I can handle transcript generation and evaluation metrics.
Aaleya: Also, we should clearly highlight urgency-based tasks in the UI.
Dev: That's actually our differentiator. Judges like clarity.
Yash: What's the tech stack final call?
Dev: Python backend, FastAPI, Cohere or open-source fallback.
Farhaan: We should keep an offline fallback in case APIs fail.
Aaleya: Timeline check: backend MVP by day five?
Yash: That's tight but doable if scope doesn't change.
Dev: Then frontend integration day six and seven.
Farhaan: Final two days for polish and pitch.
Aaleya: Speaking of pitch, who's presenting?
Dev: I can lead, but Farhaan should cover the technical depth.
Farhaan: Sure, but we need a strong story, not just architecture.
Yash: Story should be about reducing meeting fatigue and missed action items.
Aaleya: Exactly. Less talk, more outcomes.
Dev: Okay, action items are clear. Let's sync daily until the hackathon.
"""

# Cell 4: Parse Transcript
def parse_transcript_with_timestamps(raw_text, start_time=0, avg_gap=30):
    """
    Parse raw transcript and add timestamps

    Args:
        raw_text: Raw transcript string
        start_time: Starting timestamp in seconds
        avg_gap: Average seconds between messages
    """
    lines = [line.strip() for line in raw_text.strip().split('\n') if line.strip()]
    transcript = []
    current_time = start_time

    for line in lines:
        if ':' in line:
            parts = line.split(':', 1)
            speaker = parts[0].strip()
            text = parts[1].strip()

            timestamp = str(timedelta(seconds=current_time))

            transcript.append({
                "timestamp": timestamp,
                "speaker_name": speaker,
                "text": text,
                "sentiment": None  # Will be filled later
            })

            # Increment time based on text length
            current_time += avg_gap + len(text) // 10

    return transcript

transcript = parse_transcript_with_timestamps(RAW_TRANSCRIPT)

print(f"\n✓ Parsed {len(transcript)} transcript entries with timestamps")
print("\nFirst 3 entries:")
for entry in transcript[:3]:
    print(f"[{entry['timestamp']}] {entry['speaker_name']}: {entry['text']}")

# Cell 5: Create/Verify Qdrant Collection
def create_or_verify_collection():
    """
    Create Qdrant collection if it doesn't exist
    """
    try:
        collections = qdrant_client.get_collections().collections
        collection_names = [col.name for col in collections]

        if COLLECTION_NAME in collection_names:
            print(f"✓ Collection '{COLLECTION_NAME}' already exists")
            collection_info = qdrant_client.get_collection(COLLECTION_NAME)
            print(f"  Points count: {collection_info.points_count}")
        else:
            qdrant_client.create_collection(
                collection_name=COLLECTION_NAME,
                vectors_config=VectorParams(size=EMBEDDING_DIM, distance=Distance.COSINE),
            )
            print(f"✓ Created new collection: {COLLECTION_NAME}")
    except Exception as e:
        print(f"⚠ Error with collection: {e}")

create_or_verify_collection()

# Cell 6: Generate Embeddings with Sentence Transformers
def generate_embeddings(texts):
    """
    Generate embeddings using Sentence Transformers
    """
    embeddings = embedding_model.encode(texts, show_progress_bar=True)
    return embeddings.tolist()

def store_transcript_in_qdrant(transcript, meeting_id):
    """
    Store transcript entries in Qdrant with embeddings
    """
    # Prepare texts for embedding
    texts = [f"{entry['speaker_name']}: {entry['text']}" for entry in transcript]

    print(f"\nGenerating embeddings for {len(texts)} transcript entries...")
    embeddings = generate_embeddings(texts)

    # Prepare points for Qdrant
    points = []
    for i, (entry, embedding) in enumerate(zip(transcript, embeddings)):
        point = PointStruct(
            id=str(uuid.uuid4()),
            vector=embedding,
            payload={
                "meeting_id": meeting_id,
                "timestamp": entry["timestamp"],
                "speaker_name": entry["speaker_name"],
                "text": entry["text"],
                "sentiment": entry.get("sentiment", "neutral"),
                "entry_index": i
            }
        )
        points.append(point)

    # Upload to Qdrant in batches
    batch_size = 100
    for i in range(0, len(points), batch_size):
        batch = points[i:i + batch_size]
        qdrant_client.upsert(
            collection_name=COLLECTION_NAME,
            points=batch
        )
        print(f"  Uploaded batch {i//batch_size + 1}/{(len(points)-1)//batch_size + 1}")

    print(f"✓ Stored {len(points)} transcript entries in Qdrant Cloud")
    return points

# Cell 7: LLM-Based Urgency Detection
def compute_urgency_with_llm(task):
    """
    Use LLM to determine urgency level based on task context

    Returns: critical, high, medium, or low
    """
    system_prompt = """You are an expert project manager analyzing task urgency.
    Evaluate the urgency level based on:
    - Deadline proximity
    - Impact on project/team
    - Dependencies and blockers
    - Language indicators (ASAP, critical, etc.)
    - Business context

    Respond with ONLY ONE WORD: critical, high, medium, or low"""

    task_description = f"""
Task: {task.get('task', 'N/A')}
Owner: {task.get('owner', 'N/A')}
Deadline: {task.get('deadline', 'N/A')}
Context: {task.get('urgency_reason', 'N/A')}
"""

    try:
        response = co.chat(
            model="command-r-v2",
            preamble=system_prompt,
            message=f"Determine urgency level for this task:\n{task_description}",
            temperature=0.2,
            max_tokens=10
        )

        urgency = response.text.strip().lower()

        # Ensure valid urgency level
        if urgency not in ['critical', 'high', 'medium', 'low']:
            urgency = 'medium'

        return urgency
    except Exception as e:
        print(f"Warning: Urgency detection failed. Using default 'medium'. Error: {e}")
        return 'medium'

print("✓ LLM-based urgency detection ready")

# Cell 8: Meeting Summary with LLM
def summarize_with_urgency(transcript_text):
    """
    Use Cohere LLM to extract structured meeting insights
    """
    system_prompt = """You are an enterprise AI meeting assistant.
    Extract structured information from meeting transcripts in valid JSON format.

    Focus on:
    - Executive summary (2-3 sentences)
    - Action items with task, owner, deadline (ISO format if mentioned), and urgency_reason
    - Topics discussed
    - Named entities (people, systems, tools)
    - Overall meeting sentiment

    For urgency_reason, provide detailed context about:
    - Why the task is important
    - Any mentioned deadlines or time pressures
    - Dependencies or blockers
    - Impact on the project
    """

    user_prompt = f"""Analyze this meeting transcript and return ONLY valid JSON:

Transcript:
{transcript_text}

Required JSON structure:
{{
  "executive_summary": "brief overview",
  "action_items": [
    {{
      "task": "description",
      "owner": "person name",
      "deadline": "YYYY-MM-DD or null",
      "urgency_reason": "detailed explanation of task importance, context, and time sensitivity"
    }}
  ],
  "topics_discussed": ["topic1", "topic2"],
  "named_entities": ["entity1", "entity2"],
  "overall_sentiment": "positive/neutral/negative"
}}

Return ONLY the JSON object, no markdown formatting."""

    response = co.chat(
        model="command-r-v2",
        preamble=system_prompt,
        message=user_prompt,
        temperature=0.2,
        max_tokens=1500
    )

    return response.text

# Format transcript for LLM
transcript_text = "\n".join(
    f"[{t['timestamp']}] {t['speaker_name']}: {t['text']}"
    for t in transcript
)

print("✓ Summarization function ready")

# Cell 9: Generate Meeting Summary
print("\n" + "="*60)
print("ANALYZING MEETING TRANSCRIPT")
print("="*60)

llm_raw = summarize_with_urgency(transcript_text)

# Clean potential markdown formatting
if llm_raw.strip().startswith('```json'):
    llm_raw = llm_raw.strip()[len('```json'):-len('```')].strip()
elif llm_raw.strip().startswith('```'):
    llm_raw = llm_raw.strip()[3:-3].strip()

# Parse JSON
try:
    llm_output = json.loads(llm_raw)
    print("✓ Meeting summary generated successfully")
except json.JSONDecodeError as e:
    print(f"⚠ JSON parsing error: {e}")
    print("Raw output:", llm_raw[:500])
    llm_output = {
        "executive_summary": "Error parsing summary",
        "action_items": [],
        "topics_discussed": [],
        "named_entities": [],
        "overall_sentiment": "neutral"
    }

# Apply LLM-based urgency computation to each action item
print("\nComputing urgency levels with LLM...")
for i, task in enumerate(llm_output.get("action_items", []), 1):
    print(f"  Analyzing urgency for task {i}/{len(llm_output.get('action_items', []))}...")
    task["urgency"] = compute_urgency_with_llm(task)

print("\n✓ Urgency analysis complete")
print("\nMeeting Summary:")
print(json.dumps(llm_output, indent=2))

# Cell 10: Sentiment Analysis
import time

def analyze_sentiment(text):
    """
    Analyze sentiment of individual message using LLM
    """
    system_prompt = """You are a sentiment analyzer. Analyze the sentiment of the given text.
    Respond with ONLY ONE WORD: positive, neutral, or negative."""

    response = co.chat(
        model="command-r-v2",
        preamble=system_prompt,
        message=f"Analyze sentiment: '{text}'",
        temperature=0.1,
        max_tokens=5
    )

    sentiment = response.text.strip().lower()

    # Ensure valid sentiment
    if sentiment not in ['positive', 'neutral', 'negative']:
        sentiment = 'neutral'

    return sentiment

print("\n" + "="*60)
print("ANALYZING SENTIMENT FOR EACH MESSAGE")
print("="*60)

for i, entry in enumerate(transcript):
    entry['sentiment'] = analyze_sentiment(entry['text'])
    # Add a small delay to avoid hitting rate limits for trial keys
    time.sleep(0.5) # Wait for 0.5 seconds between API calls
    if (i + 1) % 5 == 0:
        print(f"  Processed {i + 1}/{len(transcript)} messages...")

print("✓ Sentiment analysis complete")

# Cell 11: Store in Qdrant Cloud
meeting_id = f"mtg_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
print(f"\n{'='*60}")
print(f"STORING TRANSCRIPT IN QDRANT CLOUD")
print(f"{'='*60}")
print(f"Meeting ID: {meeting_id}")

stored_points = store_transcript_in_qdrant(transcript, meeting_id)

# Cell 12: Semantic Search Functions
def search_relevant_transcript(query, meeting_id, top_k=5):
    """
    Search for relevant transcript entries using semantic search in Qdrant
    """
    # Generate embedding for the query
    query_embedding = embedding_model.encode([query])[0].tolist()

    # Search in Qdrant
    search_results = qdrant_client.search(
        collection_name=COLLECTION_NAME,
        query_vector=query_embedding,
        query_filter={
            "must": [
                {
                    "key": "meeting_id",
                    "match": {"value": meeting_id}
                }
            ]
        },
        limit=top_k
    )

    return search_results

def chat_with_transcript(user_question, processed_data, use_semantic_search=True):
    """
    Answer user questions based on meeting data using LLM with semantic search
    """
    transcript = processed_data.get('transcript', [])
    summary = processed_data.get('summary', {})
    meeting_id = processed_data.get('meeting_id')

    # Use semantic search to find most relevant parts
    relevant_context = ""
    if use_semantic_search and meeting_id:
        try:
            search_results = search_relevant_transcript(user_question, meeting_id, top_k=5)
            relevant_context = "\n\nMOST RELEVANT TRANSCRIPT SECTIONS (Semantic Search):\n"
            for i, result in enumerate(search_results, 1):
                payload = result.payload
                relevant_context += f"{i}. [{payload['timestamp']}] {payload['speaker_name']}: {payload['text']} (Relevance: {result.score:.3f})\n"
        except Exception as e:
            print(f"Semantic search warning: {e}")

    # Format full transcript with sentiment
    formatted_transcript = "\n".join(
        f"[{t['timestamp']}] {t['speaker_name']} (Sentiment: {t['sentiment']}): {t['text']}"
        for t in transcript
    )

    # Format summary
    formatted_summary = f"""
EXECUTIVE SUMMARY:
{summary.get('executive_summary', 'N/A')}

ACTION ITEMS:
"""
    for i, item in enumerate(summary.get('action_items', []), 1):
        formatted_summary += f"""
{i}. Task: {item.get('task', 'N/A')}
   Owner: {item.get('owner', 'N/A')}
   Deadline: {item.get('deadline', 'N/A')}
   Urgency: {item.get('urgency', 'N/A')}
   Reason: {item.get('urgency_reason', 'N/A')}
"""

    formatted_summary += f"""
TOPICS DISCUSSED: {', '.join(summary.get('topics_discussed', ['N/A']))}
NAMED ENTITIES: {', '.join(summary.get('named_entities', ['N/A']))}
OVERALL SENTIMENT: {summary.get('overall_sentiment', 'N/A')}
"""

    system_prompt = """You are an AI meeting assistant. Answer questions based ONLY on the provided meeting data.
    Be concise and accurate. If information is not available, say so clearly.
    Reference specific timestamps and speakers when relevant.
    Prioritize information from the most relevant sections when available."""

    user_message = f"""
FULL MEETING TRANSCRIPT:
{formatted_transcript}

MEETING SUMMARY:
{formatted_summary}
{relevant_context}

USER QUESTION: {user_question}

Provide a clear, concise answer based on the meeting data above. Use the relevant sections highlighted by semantic search for better context."""

    response = co.chat(
        model="command-r-v2",
        preamble=system_prompt,
        message=user_message,
        temperature=0.3,
        max_tokens=500
    )

    return response.text

print("✓ Enhanced chat interface with semantic search ready")

# Cell 13: Create Processed Meeting Data
processed_meeting_data = {
    "meeting_id": meeting_id,
    "timestamp": datetime.now().isoformat(),
    "overall_sentiment": llm_output.get("overall_sentiment", "neutral"),
    "transcript": transcript,
    "summary": llm_output,
    "qdrant_stored": True,
    "qdrant_url": QDRANT_URL,
    "total_entries_stored": len(stored_points)
}

print("\n" + "="*60)
print("MEETING DATA PROCESSED")
print("="*60)
print(f"Meeting ID: {processed_meeting_data['meeting_id']}")
print(f"Total messages: {len(transcript)}")
print(f"Action items: {len(llm_output.get('action_items', []))}")
print(f"Overall sentiment: {processed_meeting_data['overall_sentiment']}")
print(f"Stored in Qdrant Cloud: {processed_meeting_data['qdrant_stored']}")
print(f"Total entries in Qdrant: {processed_meeting_data['total_entries_stored']}")

# Cell 14: Demo Q&A
print("\n" + "="*60)
print("SAMPLE Q&A DEMO")
print("="*60)

questions = [
    "What are the main action items and their urgency levels?",
    "Who is responsible for the backend?",
    "What concerns did the team raise?",
    "What is the timeline for the hackathon?"
]

for i, question in enumerate(questions, 1):
    print(f"\n[Q{i}] {question}")
    print("-" * 60)
    answer = chat_with_transcript(question, processed_meeting_data)
    print(f"[A{i}] {answer}")

# Cell 15: Export Results
def export_meeting_analysis(data, filename="meeting_analysis.json"):
    """Export meeting analysis to JSON file"""
    # Create a copy without embedding model reference
    export_data = {
        "meeting_id": data["meeting_id"],
        "timestamp": data["timestamp"],
        "overall_sentiment": data["overall_sentiment"],
        "summary": data["summary"],
        "qdrant_stored": data["qdrant_stored"],
        "total_entries_stored": data["total_entries_stored"],
        "transcript_sample": data["transcript"][:5]  # First 5 entries for reference
    }

    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(export_data, f, indent=2, ensure_ascii=False)
    print(f"\n✓ Meeting analysis exported to {filename}")

export_meeting_analysis(processed_meeting_data)

# Cell 15: Export Results
def export_meeting_analysis(data, filename="meeting_analysis.json"):
    """Export meeting analysis to JSON file"""
    # Create a copy without embedding model reference
    export_data = {
        "meeting_id": data["meeting_id"],
        "timestamp": data["timestamp"],
        "overall_sentiment": data["overall_sentiment"],
        "summary": data["summary"],
        "qdrant_stored": data["qdrant_stored"],
        "total_entries_stored": data["total_entries_stored"],
        "transcript_sample": data["transcript"][:5]  # First 5 entries for reference
    }

    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(export_data, f, indent=2, ensure_ascii=False)
    print(f"\n✓ Meeting analysis exported to {filename}")

export_meeting_analysis(processed_meeting_data)

# Cell 16: Interactive Chat Session
def interactive_chat():
    """Start an interactive chat session with semantic search"""
    print("\n" + "="*60)
    print("🤖 INTERACTIVE MEETING ASSISTANT")
    print("="*60)
    print("Ask questions about the meeting using natural language.")
    print("✨ Powered by Qdrant Cloud + Sentence Transformers + Cohere LLM")
    print("\n📋 Available Commands:")
    print("  • 'exit', 'quit', 'bye' - End chat session")
    print("  • 'summary' - Quick meeting overview")
    print("  • 'search <query>' - Semantic search in transcript")
    print("  • 'stats' - Qdrant storage statistics")
    print("  • 'actions' - List all action items with urgency")
    print("="*60 + "\n")

    while True:
        try:
            user_input = input("You: ").strip()

            if not user_input:
                continue

            if user_input.lower() in ['exit', 'quit', 'bye']:
                print("\n✓ Chat session ended. Thank you! 👋")
                break

            # Quick summary command
            if user_input.lower() == 'summary':
                print(f"\n🤖 Assistant: Here's your meeting overview:")
                print(f"\n📝 Executive Summary:")
                print(f"   {processed_meeting_data['summary'].get('executive_summary', 'N/A')}")
                print(f"\n📊 Statistics:")
                print(f"   • Action Items: {len(processed_meeting_data['summary'].get('action_items', []))}")
                print(f"   • Overall Sentiment: {processed_meeting_data['overall_sentiment']}")
                print(f"   • Topics: {', '.join(processed_meeting_data['summary'].get('topics_discussed', ['N/A']))}")
                print(f"   • Participants: {', '.join(processed_meeting_data['summary'].get('named_entities', ['N/A']))}\n")
                continue

            # Actions command
            if user_input.lower() == 'actions':
                print(f"\n🤖 Assistant: Here are all action items:\n")
                for i, item in enumerate(processed_meeting_data['summary'].get('action_items', []), 1):
                    urgency_emoji = {
                        'critical': '🔴',
                        'high': '🟠',
                        'medium': '🟡',
                        'low': '🟢'
                    }.get(item.get('urgency', 'medium'), '⚪')

                    print(f"{i}. {urgency_emoji} [{item.get('urgency', 'N/A').upper()}] {item.get('task', 'N/A')}")
                    print(f"   👤 Owner: {item.get('owner', 'N/A')}")
                    print(f"   📅 Deadline: {item.get('deadline', 'Not specified')}")
                    print(f"   💡 Reason: {item.get('urgency_reason', 'N/A')}\n")
                continue

            # Stats command
            if user_input.lower() == 'stats':
                try:
                    collection_info = qdrant_client.get_collection(COLLECTION_NAME)
                    print(f"\n🤖 Assistant: Qdrant Cloud Storage Statistics:")
                    print(f"   • Collection: {COLLECTION_NAME}")
                    print(f"   • Total vectors: {collection_info.points_count}")
                    print(f"   • Vector dimension: {collection_info.config.params.vectors.size}")
                    print(f"   • Distance metric: {collection_info.config.params.vectors.distance}")
                    print(f"   • Current Meeting ID: {processed_meeting_data['meeting_id']}")
                    print(f"   • Embedding Model: all-MiniLM-L6-v2\n")
                except Exception as e:
                    print(f"\n⚠ Error fetching stats: {e}\n")
                continue

            # Semantic search command
            if user_input.lower().startswith('search '):
                query = user_input[7:].strip()
                if query:
                    print(f"\n🔍 Searching for: '{query}'...\n")
                    results = search_relevant_transcript(query, processed_meeting_data['meeting_id'], top_k=3)
                    print(f"🤖 Assistant: Top 3 most relevant transcript sections:\n")
                    for i, result in enumerate(results, 1):
                        payload = result.payload
                        print(f"{i}. [{payload['timestamp']}] 💬 {payload['speaker_name']}:")
                        print(f"   \"{payload['text']}\"")
                        print(f"   📊 Relevance Score: {result.score:.3f}\n")
                continue

            # Regular question - use LLM with semantic search
            print(f"\n🔍 Analyzing your question...\n")
            response = chat_with_transcript(user_input, processed_meeting_data, use_semantic_search=True)
            print(f"🤖 Assistant: {response}\n")

        except KeyboardInterrupt:
            print("\n\n✓ Chat interrupted. Goodbye! 👋")
            break
        except Exception as e:
            print(f"\n⚠ Error: {e}")
            print("Please try again or type 'exit' to quit.\n")

# Start interactive chat
print("\n" + "="*60)
print("🚀 STARTING INTERACTIVE CHAT SESSION")
print("="*60)

interactive_chat()